name: Deploy Docusaurus with SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: docs-site
        run: npm ci

      - name: Build Docusaurus
        working-directory: docs-site
        run: npm run build

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to GitHub Pages via SSH
        working-directory: docs-site
        env:
          USE_SSH: true  # ✅ SSH 모드 활성화
          GIT_USER: github-actions[bot]
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          npx docusaurus deploy
