name: Deploy Docusaurus to gh-pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        working-directory: docs-site
        run: npm ci

      - name: Build Docusaurus
        working-directory: docs-site
        run: npm run build

      - name: Configure Git Identity & Remote
        working-directory: docs-site
        env:
          GIT_USER: hyunhwa
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # ✅ 명시적으로 remote 인증 포함
          git remote set-url origin https://${GIT_USER}:${GITHUB_TOKEN}@github.com/BnsHyun/I_nori.git

      - name: Deploy to GitHub Pages
        working-directory: docs-site
        env:
          GIT_USER: hyunhwa
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx docusaurus deploy
