name: Deploy Docusaurus to gh-pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Install deps & build
        working-directory: docs-site
        run: |
          npm ci
          npm run build

      - name: Deploy to GitHub Pages
        working-directory: docs-site
        env:
          GIT_USER: x-access-token
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/BnsHyun/I_nori.git
          npx docusaurus deploy
