name: Docs Check

on:
  pull_request:
    paths:
      - 'docs-site/docs/**'
      - '.github/**'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Markdown Linter
        uses: DavidAnson/markdownlint-cli2-action@v15
        with:
          globs: 'docs-site/docs/**/*.md'
